### ISSUE TITLE
add short descriptions of functionality below visuals

### ISSUE THREAD

**Issue by gernotstarke** [arc42/PDFminion#24]
similar to shottr:

![Image](https://github.com/user-attachments/assets/4931fcfc-8554-4828-b76b-8b26d6c87d8d)

* we have to reduce the size of the png-images
* we have to add a textual header
* we have to add (small-font) explanations

**Comment by Per-Starke** [comment]
- added .img-half class to the images, so they fill only slightly less than half of the container width, instead of full width. The percentage can be controlled via the class in custom-styles.css, but I think 40% is a good starting point for now. Also included small top margin, to the images don't stick directly to the borders of the boxes

- Added h5-s below the images, for textual headers

- Added normal p-tags below the headers for explanations. If you find this too large, we can also use small-tags, but I think the normal text size here works really well and smaller text would be not well readable anymore

@gernotstarke
